
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2276
Not Found: /apple-touch-icon-precomposed.png
"GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 2390
Not Found: /apple-touch-icon.png
"GET /apple-touch-icon.png HTTP/1.1" 404 2354
"GET /lesson1/ HTTP/1.1" 200 13
"GET /lesson2/ HTTP/1.1" 200 13
"GET /lesson2/user HTTP/1.1" 301 0
Internal Server Error: /lesson2/user/
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'else'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 19, in user
    return render(request, "user.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 23: 'else', expected 'endblock'. Did you forget to register or load this tag?
"GET /lesson2/user/ HTTP/1.1" 500 161862
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'else'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 19, in user
    return render(request, "user.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 23: 'else', expected 'endblock'. Did you forget to register or load this tag?
"GET /lesson2/user/ HTTP/1.1" 500 162023
Internal Server Error: /lesson2/user/
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'else'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 19, in user
    return render(request, "user.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 23: 'else', expected 'endblock'. Did you forget to register or load this tag?
"GET /lesson2/user/ HTTP/1.1" 500 162023
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2276
"GET /lesson2/ HTTP/1.1" 200 13
"GET /lesson2/user/ HTTP/1.1" 200 288
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2276
Internal Server Error: /lesson2/user/
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 19, in user
    user = get_object_or_404(User)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 640, in get
    raise self.model.MultipleObjectsReturned(
lesson2.models.User.MultipleObjectsReturned: get() returned more than one User -- it returned more than 20!
"GET /lesson2/user/ HTTP/1.1" 500 74247
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2276
"GET /lesson2/user/ HTTP/1.1" 200 27231
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2276
"GET /lesson2/ HTTP/1.1" 200 13
"GET /lesson2/user/ HTTP/1.1" 200 288
"GET /lesson2/user/ HTTP/1.1" 200 288
"GET /lesson2/ HTTP/1.1" 200 13
"GET /lesson2/order HTTP/1.1" 301 0
"GET /lesson2/order/ HTTP/1.1" 200 276
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2276
"GET /lesson2/order/ HTTP/1.1" 200 276
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/order/ HTTP/1.1" 200 5012
Watching for file changes with StatReloader
Internal Server Error: /lesson2/order/
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 30, in get_all_order
    return render(request, "order.html", {'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '()' from 'order.products.all()'
"GET /lesson2/order/ HTTP/1.1" 500 209721
Watching for file changes with StatReloader
Internal Server Error: /lesson2/order/
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 30, in get_all_order
    return render(request, "order.html", {'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '().values_list()' from 'order.products.all().values_list()'
"GET /lesson2/order/ HTTP/1.1" 500 209987
Watching for file changes with StatReloader
Internal Server Error: /lesson2/order/
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 30, in get_all_order
    return render(request, "order.html", {'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 193, in render
    values = list(values)
             ^^^^^^^^^^^^
TypeError: 'ManyRelatedManager' object is not iterable
"GET /lesson2/order/ HTTP/1.1" 500 235632
Watching for file changes with StatReloader
"GET /lesson2/order/ HTTP/1.1" 200 6455
Watching for file changes with StatReloader
"GET /lesson2/order/ HTTP/1.1" 200 5543
Watching for file changes with StatReloader
"GET /lesson2/order/ HTTP/1.1" 200 5699
Watching for file changes with StatReloader
"GET /lesson2/order/ HTTP/1.1" 200 4817
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dasa/Documents/geekbrains/Django/project/lesson2/urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /lesson2/order/ HTTP/1.1" 200 4817
"GET /lesson2/ HTTP/1.1" 200 13
"GET /lesson2/user/ HTTP/1.1" 200 2753
Not Found: /lesson2/user_orders/1
"GET /lesson2/user_orders/1 HTTP/1.1" 404 3157
"GET /lesson2/user/1 HTTP/1.1" 301 0
"GET /lesson2/user/1/ HTTP/1.1" 200 897
"GET /lesson2/user/1/ HTTP/1.1" 200 951
"GET /lesson2/user/1/ HTTP/1.1" 200 902
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dasa/Documents/geekbrains/Django/project/lesson2/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/ HTTP/1.1" 200 902
Internal Server Error: /lesson2/user/1/1
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: user_fillter_products() got an unexpected keyword argument 'date'
"GET /lesson2/user/1/1 HTTP/1.1" 500 57741
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/1
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 42, in user_fillter_products
    products = set(order.products.all)
               ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'method' object is not iterable
"GET /lesson2/user/1/1 HTTP/1.1" 500 62032
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/1
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 42, in user_fillter_products
    products = set(order.products)
               ^^^^^^^^^^^^^^^^^^^
TypeError: 'ManyRelatedManager' object is not iterable
"GET /lesson2/user/1/1 HTTP/1.1" 500 62064
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/1
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 42, in user_fillter_products
    products = set(order)
               ^^^^^^^^^^
TypeError: 'Order' object is not iterable
"GET /lesson2/user/1/1 HTTP/1.1" 500 61976
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/1
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 43, in user_fillter_products
    return render(request, 'user_products_orders.html', {'user': user, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: user_products_orders.html
"GET /lesson2/user/1/1 HTTP/1.1" 500 77968
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/1
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 42, in user_fillter_products
    products = set(order.products.all)
               ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'method' object is not iterable
"GET /lesson2/user/1/1 HTTP/1.1" 500 62032
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/1
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 42, in user_fillter_products
    products = set(order.products.all)
               ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'method' object is not iterable
"GET /lesson2/user/1/1 HTTP/1.1" 500 62032
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/1
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 43, in user_fillter_products
    return render(request, 'user_products_orders.html', {'user': user, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: user_products_orders.html
"GET /lesson2/user/1/1 HTTP/1.1" 500 77981
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/1 HTTP/1.1" 200 464
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/1 HTTP/1.1" 200 464
"GET /lesson2/user/1/1 HTTP/1.1" 200 464
"GET /lesson2/user/1/ HTTP/1.1" 200 902
"GET /lesson2/user/1/300 HTTP/1.1" 200 464
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/300 HTTP/1.1" 200 350
"GET /lesson2/user/1/300 HTTP/1.1" 200 350
"GET /lesson2/user/1/ HTTP/1.1" 200 902
"GET /lesson2/user/1/1 HTTP/1.1" 200 350
"GET /lesson2/user/1/1 HTTP/1.1" 200 350
"GET /lesson2/user/1/ HTTP/1.1" 200 902
"GET /lesson2/user/1/0 HTTP/1.1" 200 464
"GET /lesson2/user/1/0 HTTP/1.1" 200 587
/Users/dasa/Documents/geekbrains/Django/project/lesson2/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /lesson2/user/1/0 HTTP/1.1" 200 432
Watching for file changes with StatReloader
"GET /lesson2/user/1/0 HTTP/1.1" 200 432
"GET /lesson2/user/1/ HTTP/1.1" 200 903
"GET /lesson2/user/1/1 HTTP/1.1" 200 350
"GET /lesson2/user/1/ HTTP/1.1" 200 903
"GET /lesson2/user/1/300 HTTP/1.1" 200 350
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/300 HTTP/1.1" 200 589
"GET /lesson2/user/1/300 HTTP/1.1" 200 589
"GET /lesson2/user/1/30 HTTP/1.1" 200 589
"GET /lesson2/user/1/30 HTTP/1.1" 200 589
"GET /lesson2/user/1/ HTTP/1.1" 200 903
"GET /lesson2/user/1/1 HTTP/1.1" 200 589
"GET /lesson2/user/1/ HTTP/1.1" 200 903
"GET /lesson2/user/1/7 HTTP/1.1" 200 589
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/7
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 42, in user_fillter_products
    orders = Order.objects.filter(customer=user, Order_time__year=datetime.date.today().year).order_by('-id')
                                                                  ^^^^^^^^^^^^^^^^^^^
AttributeError: 'method_descriptor' object has no attribute 'today'
"GET /lesson2/user/1/7 HTTP/1.1" 500 61899
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/7
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 42, in user_fillter_products
    orders = Order.objects.filter(customer=user, Order_time__year=datetime.date.today().year).order_by('-id')
                                                                  ^^^^^^^^^^^^^^^^^^^
AttributeError: 'method_descriptor' object has no attribute 'today'
"GET /lesson2/user/1/7 HTTP/1.1" 500 61897
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/7
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 41, in user_fillter_products
    today = datetime.date.today()
            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'method_descriptor' object has no attribute 'today'
"GET /lesson2/user/1/7 HTTP/1.1" 500 61972
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/7
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 41, in user_fillter_products
    today = datetime.date.now()
            ^^^^^^^^^^^^^^^^^
AttributeError: 'method_descriptor' object has no attribute 'now'
"GET /lesson2/user/1/7 HTTP/1.1" 500 61956
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2276
"GET /lesson2/ HTTP/1.1" 200 13
"GET /lesson2/user/1/0 HTTP/1.1" 200 507
"GET /lesson2/user/ HTTP/1.1" 200 2753
"GET /lesson2/user/1/ HTTP/1.1" 200 903
"GET /lesson2/user/1/7 HTTP/1.1" 200 589
"GET /lesson2/user/1/ HTTP/1.1" 200 903
"GET /lesson2/user/1/30 HTTP/1.1" 200 589
"GET /lesson2/user/1/365 HTTP/1.1" 200 589
"GET /lesson2/user/1/365 HTTP/1.1" 200 589
"GET /lesson2/user/1/ HTTP/1.1" 200 903
"GET /lesson2/user/1/1 HTTP/1.1" 200 589
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/1
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 43, in user_fillter_products
    orders = Order('views', filter=Q(views__customer=user, date_ordered__gte=start_date)).order_by('-id')
                                   ^
NameError: name 'Q' is not defined
"GET /lesson2/user/1/1 HTTP/1.1" 500 61744
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/1
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 44, in user_fillter_products
    orders = Order('views', filter=Q(views__customer=user, date_ordered__gte=start_date)).order_by('-id')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/db/models/base.py", line 567, in __init__
    raise TypeError(
TypeError: Order() got unexpected keyword arguments: 'filter'
"GET /lesson2/user/1/1 HTTP/1.1" 500 69029
Internal Server Error: /lesson2/user/1/1
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 44, in user_fillter_products
    orders = Order('views', filter=Q(views__customer=user, date_ordered__gte=start_date)).order_by('-id')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/db/models/base.py", line 567, in __init__
    raise TypeError(
TypeError: Order() got unexpected keyword arguments: 'filter'
"GET /lesson2/user/1/1 HTTP/1.1" 500 69029
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/1
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 44, in user_fillter_products
    orders = Order.objects.annotate('views', filter=Q(customer=user, views__date_ordered__gte=start_date)).order_by('-id')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1590, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1600, in _annotate
    self._validate_values_are_expressions(
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1950, in _validate_values_are_expressions
    raise TypeError(
TypeError: QuerySet.annotate() received non-expression(s): views.
"GET /lesson2/user/1/1 HTTP/1.1" 500 84392
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/1
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 44, in user_fillter_products
    orders = Order.objects.filter(customer=user, views__date_ordered__gte=start_date).order_by('-id')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'views' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
"GET /lesson2/user/1/1 HTTP/1.1" 500 117644
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/1 HTTP/1.1" 200 589
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/1 HTTP/1.1" 200 350
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/1
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 42, in user_fillter_products
    start = datetime.date.today() - datetime.timedelta(days=date)
            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'method_descriptor' object has no attribute 'today'
"GET /lesson2/user/1/1 HTTP/1.1" 500 61702
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/1
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 43, in user_fillter_products
    start = datetime.date.today() - datetime.timedelta(days=date)
            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'method_descriptor' object has no attribute 'today'
"GET /lesson2/user/1/1 HTTP/1.1" 500 61694
"GET /lesson2/user/1/ HTTP/1.1" 200 903
Internal Server Error: /lesson2/user/1/1
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 43, in user_fillter_products
    start = datetime.date.today() - datetime.timedelta(days=date)
            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'method_descriptor' object has no attribute 'today'
"GET /lesson2/user/1/1 HTTP/1.1" 500 61694
"GET /lesson2/user/1/ HTTP/1.1" 200 903
Internal Server Error: /lesson2/user/1/7
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 43, in user_fillter_products
    start = datetime.date.today() - datetime.timedelta(days=date)
            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'method_descriptor' object has no attribute 'today'
"GET /lesson2/user/1/7 HTTP/1.1" 500 61694
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/7
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 43, in user_fillter_products
    start = datetime.now() - datetime.timedelta(days=date)
                             ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
"GET /lesson2/user/1/7 HTTP/1.1" 500 61748
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/7 HTTP/1.1" 200 589
"GET /lesson2/user/1/ HTTP/1.1" 200 903
"GET /lesson2/user/1/20 HTTP/1.1" 200 589
"GET /lesson2/user/1/20 HTTP/1.1" 200 589
"GET /lesson2/user/1/ HTTP/1.1" 200 903
"GET /lesson2/user/1/400 HTTP/1.1" 200 589
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/400
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 47, in user_fillter_products
    print(orders.date_ordered)
          ^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'date_ordered'
"GET /lesson2/user/1/400 HTTP/1.1" 500 62022
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/400 HTTP/1.1" 200 589
"GET /lesson2/user/1/400 HTTP/1.1" 200 589
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/400 HTTP/1.1" 200 350
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/400 HTTP/1.1" 200 589
"GET /lesson2/user/1/400 HTTP/1.1" 200 580
"GET /lesson2/user/1/400 HTTP/1.1" 200 568
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/400 HTTP/1.1" 200 568
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/400
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 41, in user_fillter_products
    start = datetime.today(tz=timezone.utc) - timedelta(days=date)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: datetime.today() takes no keyword arguments
"GET /lesson2/user/1/400 HTTP/1.1" 500 61454
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/400 HTTP/1.1" 200 568
/Users/dasa/Documents/geekbrains/Django/project/project/settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/400 HTTP/1.1" 200 568
"GET /lesson2/user/1/1 HTTP/1.1" 200 568
"GET /lesson2/user/1/30 HTTP/1.1" 200 568
Not Found: /lesson2/user/1/-10
"GET /lesson2/user/1/-10 HTTP/1.1" 404 3374
"GET /lesson2/user/1/1 HTTP/1.1" 200 568
/Users/dasa/Documents/geekbrains/Django/project/project/settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2276
"GET /lesson2/user/1/1 HTTP/1.1" 200 568
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/1 HTTP/1.1" 200 568
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/1 HTTP/1.1" 200 568
"GET /lesson2/user/1/1000 HTTP/1.1" 200 568
"GET /lesson2/user/1/100 HTTP/1.1" 200 568
"GET /lesson2/user/1/10 HTTP/1.1" 200 568
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/10 HTTP/1.1" 200 568
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lesson2/user/1/10
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 42, in user_fillter_products
    start1 = datetime.date.today() - datetime.timedelta(days=date)
             ^^^^^^^^^^^^^^^^^^^
AttributeError: 'method_descriptor' object has no attribute 'today'
"GET /lesson2/user/1/10 HTTP/1.1" 500 61591
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/10 HTTP/1.1" 200 568
"GET /lesson2/user/1/7 HTTP/1.1" 200 568
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/7 HTTP/1.1" 200 568
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/7 HTTP/1.1" 200 350
"GET /lesson2/user/1/10000 HTTP/1.1" 200 350
"GET /lesson2/user/1/1000 HTTP/1.1" 200 350
/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lesson2/user/1/1000 HTTP/1.1" 200 568
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2276
Internal Server Error: /lesson2/
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 16, in index
    logger.info('Пользователь успешно зашел: ' + str(datetime.now()))
                                                     ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
"GET /lesson2/ HTTP/1.1" 500 61373
"GET /lesson2/user/1/1 HTTP/1.1" 200 491
Internal Server Error: /lesson2/user/
Traceback (most recent call last):
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dasa/Documents/geekbrains/Django/project/lesson2/views.py", line 20, in get_all_user
    logger.info('Пользователь успешно зашел: ' + str(datetime.now()))
                                                     ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
"GET /lesson2/user/ HTTP/1.1" 500 61525
"GET /lesson2/user/1/ HTTP/1.1" 200 902
"GET /lesson2/user/1/7 HTTP/1.1" 200 491
"GET /lesson2/user/1/ HTTP/1.1" 200 902
"GET /lesson2/user/1/365 HTTP/1.1" 200 491
"GET /lesson2/user/1/366 HTTP/1.1" 200 491
"GET /lesson2/user/1/366 HTTP/1.1" 200 491
"GET /lesson2/user/1/ HTTP/1.1" 200 902
"GET /lesson2/user/1/400 HTTP/1.1" 200 491
"GET /lesson2/user/1/4000 HTTP/1.1" 200 566
"GET /lesson2/user/1/4000 HTTP/1.1" 200 566
"GET /lesson2/user/1/ HTTP/1.1" 200 902
"GET /lesson2/user/1/7 HTTP/1.1" 200 350
"GET /lesson2/user/1/7 HTTP/1.1" 200 350
"GET /lesson2/user/1/ HTTP/1.1" 200 902
"GET /lesson2/user/1/8 HTTP/1.1" 200 350
"GET /lesson2/user/1/8 HTTP/1.1" 200 350
"GET /lesson2/user/1/ HTTP/1.1" 200 902
"GET /lesson2/user/1/9 HTTP/1.1" 200 491
